// Ghana Lands - Shared Enums
// Must match Prisma schema enums

export enum AccountStatus {
  ACTIVE = 'ACTIVE',
  SUSPENDED = 'SUSPENDED',
  DEACTIVATED = 'DEACTIVATED',
  PENDING_VERIFICATION = 'PENDING_VERIFICATION',
}

export enum LandCategory {
  RESIDENTIAL = 'RESIDENTIAL',
  COMMERCIAL = 'COMMERCIAL',
  INDUSTRIAL = 'INDUSTRIAL',
  AGRICULTURAL = 'AGRICULTURAL',
  MIXED_USE = 'MIXED_USE',
}

export enum LandType {
  CUSTOMARY = 'CUSTOMARY',
  TITLED = 'TITLED',
  LEASEHOLD = 'LEASEHOLD',
  FREEHOLD = 'FREEHOLD',
  GOVERNMENT = 'GOVERNMENT',
}

export enum TenureType {
  FREEHOLD = 'FREEHOLD',
  LEASEHOLD = 'LEASEHOLD',
  CUSTOMARY = 'CUSTOMARY',
}

export enum ListingStatus {
  DRAFT = 'DRAFT',
  SUBMITTED = 'SUBMITTED',
  UNDER_REVIEW = 'UNDER_REVIEW',
  PUBLISHED = 'PUBLISHED',
  SUSPENDED = 'SUSPENDED',
  REJECTED = 'REJECTED',
  SOLD = 'SOLD',
  ARCHIVED = 'ARCHIVED',
}

export enum VerificationStatus {
  UNVERIFIED = 'UNVERIFIED',
  PENDING = 'PENDING',
  IN_REVIEW = 'IN_REVIEW',
  VERIFIED = 'VERIFIED',
  REJECTED = 'REJECTED',
}

export enum VerificationRequestStatus {
  PENDING = 'PENDING',
  IN_REVIEW = 'IN_REVIEW',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  CANCELLED = 'CANCELLED',
}

export enum TransactionStatus {
  CREATED = 'CREATED',
  ESCROW_FUNDED = 'ESCROW_FUNDED',
  VERIFICATION_PERIOD = 'VERIFICATION_PERIOD',
  DISPUTED = 'DISPUTED',
  READY_TO_RELEASE = 'READY_TO_RELEASE',
  RELEASED = 'RELEASED',
  REFUNDED = 'REFUNDED',
  CANCELLED = 'CANCELLED',
  COMPLETED = 'COMPLETED',
}

export enum EscrowStatus {
  PENDING = 'PENDING',
  FUNDED = 'FUNDED',
  RELEASED = 'RELEASED',
  REFUNDED = 'REFUNDED',
}

export enum PaymentType {
  ESCROW_DEPOSIT = 'ESCROW_DEPOSIT',
  INSTALLMENT = 'INSTALLMENT',
  PLATFORM_FEE = 'PLATFORM_FEE',
  REFUND = 'REFUND',
}

export enum PaymentStatus {
  INITIATED = 'INITIATED',
  PROCESSING = 'PROCESSING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  REVERSED = 'REVERSED',
}

export enum DocumentType {
  SITE_PLAN = 'SITE_PLAN',
  TITLE_DEED = 'TITLE_DEED',
  INDENTURE = 'INDENTURE',
  SURVEY_REPORT = 'SURVEY_REPORT',
  ID_DOCUMENT = 'ID_DOCUMENT',
  PROOF_OF_OWNERSHIP = 'PROOF_OF_OWNERSHIP',
  OTHER = 'OTHER',
}

export enum MediaType {
  IMAGE = 'IMAGE',
  VIDEO = 'VIDEO',
  DOCUMENT = 'DOCUMENT',
}
